version: "3"

networks:
  php8:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginxlatest
    ports:
      - "8081:80"
    volumes: 
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - php8

  mysql:
    image: mysql:5.7.36
    container_name: mysql5
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ../mysql57:/var/lib/mysql 
    environment:
      MYSQL_DATABASE_NAME: homestead
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    networks:
      - php8

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src:/var/www/html 
    ports: 
      - "9000:9000"
    networks:
      - php8

